# Generated by Django 4.1.13 on 2024-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_predefined_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('grey', 'Grey'), ('blue', 'Blue'), ('black', 'Black'), ('yellow', 'Yellow'), ('red', 'Red'), ('white', 'White')], default='white', max_length=20),
        ),
    ]
