# Generated by Django 4.2.13 on 2024-05-24 10:45

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='attributeoptiongroup',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
