# Generated by Django 4.2.13 on 2024-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='attributimages/'),
        ),
    ]
