# Generated by Django 4.2.11 on 2024-11-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_attributeoption_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='variants',
            field=models.CharField(choices=[('------', '------'), ('colors', 'Colors'), ('materials', 'Materials')], default='------', max_length=20, verbose_name='variants'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.productclass', verbose_name='Product class'),
        ),
    ]
