# Generated by Django 4.2.11 on 2024-11-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_alter_productattribute_product_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_attribute', to='catalogue.productclass', verbose_name='variable attribute'),
        ),
    ]
