# Generated by Django 4.2.11 on 2024-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_remove_productattribute_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='variants',
            field=models.CharField(choices=[('-----', '------'), ('colors', 'Colors'), ('materials', 'Materials')], default='-----', max_length=20, verbose_name='variants'),
        ),
    ]
