# Generated by Django 4.2.11 on 2024-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_productattribute_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_a_variable_option',
            field=models.BooleanField(default=False),
        ),
    ]
