# Generated by Django 4.2.11 on 2024-11-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_option_is_a_variable_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product_class_option_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
