# Generated by Django 4.2.11 on 2024-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_productattribute_product_class_option_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('multi_select', 'Multi select'), ('checkbox', 'Checkbox'), ('locations', 'Location'), ('image', 'Image')], default='text', max_length=255, verbose_name='Type'),
        ),
    ]
