# Generated by Django 4.2.13 on 2024-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'currency'], name='partner_exc_base_cu_a95412_idx')],
                'unique_together': {('base_currency', 'currency')},
            },
        ),
    ]
