# Generated by Django 4.2.13 on 2024-06-22 19:29

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=3),
        ),
    ]
